{{- include "helm-library.configmap" (list . "test-api.configmap") -}}
{{- define "test-api.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
{{- end -}}
