environment: production
name: test-api
image: test-api

container:
  requestMemory: 5Mi
  requestCpu: 5m
  limitMemory: 40Mi
  limitCpu: 20m
  port: 3000

deployment: {}

ingress:
  host: test-api.lynxmagnus.com
